import React, { useState, useEffect, useRef } from 'react';
import { motion } from 'framer-motion';
import { CheckCircle } from 'lucide-react';

const AIStreamingOutput = ({ 
  content,          // full string from API
  isStreaming,      // boolean — true while loading
  onComplete        // callback when done
}) => {
  const [displayed, setDisplayed] = useState('');
  const [isDone, setIsDone] = useState(false);
  const indexRef = useRef(0);
  const timerRef = useRef(null);

  useEffect(() => {
    if (!content || !isStreaming) {
      setDisplayed(content || '');
      setIsDone(true);
      return;
    }

    // Reset
    setDisplayed('');
    setIsDone(false);
    indexRef.current = 0;

    // Stream character by character
    // Speed: 8ms per char — feels natural
    const stream = () => {
      if (indexRef.current < content.length) {
        setDisplayed(
          content.slice(0, indexRef.current + 1)
        );
        indexRef.current++;
        timerRef.current = setTimeout(stream, 8);
      } else {
        setIsDone(true);
        onComplete?.();
      }
    };

    timerRef.current = setTimeout(stream, 100);
    return () => clearTimeout(timerRef.current);
  }, [content, isStreaming]);

  return (
    <div className="relative">
      {/* Content area */}
      <div className="text-sm text-secondary leading-relaxed whitespace-pre-wrap font-body">
        {displayed}
        {/* Blinking cursor while streaming */}
        {!isDone && (
          <span className="inline-block w-0.5 h-4 bg-accent-violet ml-0.5 animate-blink align-middle ai-cursor" />
        )}
      </div>
      
      {/* Done indicator */}
      {isDone && content && (
        <motion.div
          initial={{ opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center gap-1.5 mt-3 text-xs text-accent-teal"
        >
          <CheckCircle size={12} />
          <span>Generated by Gemini 2.5 Flash</span>
        </motion.div>
      )}
    </div>
  );
};

export default AIStreamingOutput;
